import Head from 'next/head';
import { useEffect } from 'react';
import PageWithAuth from 'src/components/PageWithAuth';
import { apiWithAuth } from 'src/services';

export default function Home() {
  useEffect(() => {
    apiWithAuth.get('/products');
  }, []);
  return (
    <>
      <Head>
        <title>All product project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/shoppingcart_80945' />
      </Head>

      <PageWithAuth>
        <p>oi</p>
      </PageWithAuth>
    </>
  );
}
