import { Page, Document, StyleSheet, View, Text } from '@react-pdf/renderer';
import { PDFViewer } from '@react-pdf/renderer';

import Head from 'next/head';
import PageWithAuth from 'src/components/PageWithAuth';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

const PdfDocument = () => (
  <Document>
    <Page size='A4' style={styles.page}>
      <View style={styles.section}></View>
    </Page>
  </Document>
);

export default function Pdf() {
  return (
    <>
      <Head>
        <title>All product project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/shoppingcart_80945.png' />
      </Head>

      <PageWithAuth>
        <PDFViewer style={{ width: '100vw', height: '100vh' }}>
          <PdfDocument />
        </PDFViewer>
      </PageWithAuth>
    </>
  );
}
